### ISSUE TITLE
chore: readme update when 'use this template'

### ISSUE THREAD

**Issue by ahmedali8** [paulrberg/hardhat-template#136]
Make the readme file empty with only the name of new repo and reference to the template's repo instead of copying the whole existing readme as the dev would be definitely adding or removing stuff later on after 'use this template' for his own project 

this feature can be added in the create.yml file in #134

**Comment by Janther** [comment]
Hey @ahmedali8 I still like the readme describing how to use the repo.

However if you feel like changing things, I'd suggest the badges urls in the readme:

https://github.com/paulrberg/hardhat-template/actions
https://github.com/paulrberg/hardhat-template/actions/workflows/ci.yml/badge.svg

That way we can add an [Open in Gitpod button](https://www.gitpod.io/docs/getting-started#open-in-gitpod-button) as well.
I didn't add it when I added support for Gitpod because the link will prompt people on other projects to open a gitpod for this repo instead of the one created from this repo.

**Comment by ahmedali8** [comment]
@Janther created a new branch in my fork, check it out and if okay then I'll open a PR here
https://github.com/ahmedali8/hardhat-template/tree/chore/readme-update

**Comment by Janther** [comment]
This looks good, and definitely a good first step for the customisation of this template.

**Comment by ahmedali8** [comment]
Awesome, thanks @Janther 
Opening a new PR for this

**Comment by paulrberg** [comment]
Hi @ahmedali8, thanks for opening the issue. I think that you're actually proposing two unrelated changes:

1. Improve the developer experience by renaming the project to match the consumer's username.
2. Make the README file empty.

#1 is great, thanks for writing a bash script that does that. But I don't agree with #2, due to the same reasons as @Janther. We should keep the long version of the README. You might know the scripts and the commands by heart, but newcomers might not.

**Comment by ahmedali8** [comment]
Hey @paulrberg, I agree with your point of view. Please checkout my PR #137 as I have done exactly what's mentioned above in 

> 
1. Improve the developer experience by renaming the project to match the consumer's username.
