### ISSUE TITLE
ci failing on initial commit

### ISSUE THREAD

**Issue by devtooligan** [paulrberg/hardhat-template#138]
Hey PRB, thanks for all you do!

I used this template for the first time in a while and ci is failing immediately on the first commit.  The error is pretty opaque.
![Screen Shot 2022-09-12 at 10 20 20 AM](https://user-images.githubusercontent.com/71567643/189717239-936f5246-0049-470a-b92a-c4c02f91f56b.png)

Does it have to do with [this](https://github.com/paulrberg/hardhat-template/pull/135)? 🤔

**Comment by paulrberg** [comment]
Hey @devtooligan! This might be due to the `--immutable` flag, which triggers an error when you modify a dependency in `package.json` but don't subsequently run `yarn install` to update the `yarn.lock` file. As per the yarn [documentation](https://yarnpkg.com/cli/install)'s definition of `--immutable`:

>  Abort with an error exit code if the lockfile was to be modified

If this is not the reason, it might be useful to click "Fetch step" and "Link step" and report what you see. Pro tip: you can use the [Markdown collapse](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab) feature to hide the report from automatically showing in your GitHub comment.

**Comment by devtooligan** [comment]
<details>
  <summary>Woah that pro-tip!
</summary>
❤️ It's really cool! ❤️  
</details>

So what is the solution to this? I ran `yarn install` locally and it didn't seem to affect anything or update the yarn.lock.  Should I remove the `--immutable` flag from the ci.yml file??

**Comment by paulrberg** [comment]
If running `yarn install` locally didn't update `yarn.lock`, then this isn't the reason why the CI error occurs.

As you can see on line 30, the problem is that you didn't set a `MNEMONIC` environment variable in your repo's GitHub secrets. This is explained in the [README](https://github.com/paulrberg/hardhat-template/tree/985ae964f7a4856b312baea59e48715352cf394a#github-actions).

Side note: glad you like the Markdown collapse feature!

Side note 2: when you are ready to switch to Foundry, come take a look at my [Foundry Template](https://github.com/paulrberg/foundry-template). It's similar to my Hardhat Template in many ways. But one of the advantages of using Foundry is that you no longer have to provide a mnemonic to start using the template.
